### ISSUE TITLE
Minimum tasks

### ISSUE THREAD

**Issue by baijanathTharu** [baijanathTharu/nestjs-fastify-sample-ecommerce-microservices#1]
### TODO:

- [ ] Add authentication
  - [ ] Authenticate the `create order` api
  - [ ] Authenticate the `order_created` event
- [ ] Create a service to make delivery
  - [ ] The delivery service listens for `order_created` event and then sends a notification to the customer.
  - [ ] Order service will also listen for `delivery_made` event and it will update the order_status of the order to `delivered` when it occurs.
